/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , virtualroutersconfigapi = require('./virtualroutersconfig.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/tenants/config/virtual-routers-list', virtualroutersconfigapi_getVirtualRoutersList);
  app.get('/api/tenants/config/virtual-routers', virtualroutersconfigapi_getVirtualRouters);
  app.get('/api/tenants/config/virtual-routers-detail', virtualroutersconfigapi_getVirtualRoutersWithDetail);
  app.post('/api/tenants/config/virtual-routers', virtualroutersconfigapi_createVirtualRouters);
  app.put('/api/tenants/config/virtual-router/:id', virtualroutersconfigapi_updateVirtualRouters);
  app.delete('/api/tenants/config/virtual-router/:id', virtualroutersconfigapi_deleteVirtualRouters);


  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-routers-list', 'get', app.routes, 'virtualroutersconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-routers', 'get', app.routes, 'virtualroutersconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-routers-detail', 'get', app.routes, 'virtualroutersconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-routers', 'post', app.routes, 'virtualroutersconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-router/:id', 'put', app.routes, 'virtualroutersconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-router/:id', 'delete', app.routes, 'virtualroutersconfig');
}
virtualroutersconfigapi_getVirtualRoutersList = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualroutersconfigapi.getVirtualRoutersList);
  }
}
virtualroutersconfigapi_getVirtualRouters = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualroutersconfigapi.getVirtualRouters);
  }
}
virtualroutersconfigapi_getVirtualRoutersWithDetail = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualroutersconfigapi.getVirtualRoutersWithDetail);
  }
}
virtualroutersconfigapi_createVirtualRouters = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualroutersconfigapi.createVirtualRouters);
  }
}
virtualroutersconfigapi_updateVirtualRouters = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualroutersconfigapi.updateVirtualRouters);
  }
}
virtualroutersconfigapi_deleteVirtualRouters = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualroutersconfigapi.deleteVirtualRouters);
  }
}
