/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , infraDb = require('./dbnode.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/admin/monitor/infrastructure/dbnodes', infraDb_getDatabaseNodesList);
  app.get('/api/admin/monitor/infrastructure/dbnodes/summary', infraDb_getDatabaseNodesSummary);
  app.get('/api/admin/monitor/infrastructure/dbnode/details', infraDb_getDatabaseNodeDetails);
  app.get('/api/admin/monitor/infrastructure/dbnode/flow-series/stats', infraDb_getDBNodeStatsFlowSeries);
  app.get('/api/query/analytics/db/usage', infraDb_getDBUsage);
  app.get('/api/analytics/db/purge', infraDb_purgeDB);


  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/dbnodes', 'get', app.routes, 'database-node');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/dbnodes/summary', 'get', app.routes, 'database-node');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/dbnode/details', 'get', app.routes, 'database-node');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/dbnode/flow-series/stats', 'get', app.routes, 'database-node');
  parseURLReq.rbac.setFeatureByURL('/api/query/analytics/db/usage', 'get', app.routes, 'database-node');
  parseURLReq.rbac.setFeatureByURL('/api/analytics/db/purge', 'get', app.routes, 'database-node');
}
infraDb_getDatabaseNodesList = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraDb.getDatabaseNodesList);
  }
}
infraDb_getDatabaseNodesSummary = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraDb.getDatabaseNodesSummary);
  }
}
infraDb_getDatabaseNodeDetails = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraDb.getDatabaseNodeDetails);
  }
}
infraDb_getDBNodeStatsFlowSeries = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraDb.getDBNodeStatsFlowSeries);
  }
}
infraDb_getDBUsage = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraDb.getDBUsage);
  }
}
infraDb_purgeDB = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraDb.purgeDB);
  }
}
