/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , infraAna = require('./analyticsnode.api')
  , timeout = require('request-timeout')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/admin/monitor/infrastructure/analyticsnodes', infraAna_getAnalyticsNodeList);
  app.get('/api/admin/monitor/infrastructure/analyticsnodes/summary', infraAna_getAnalyticsNodeSummary);
  app.get('/api/admin/monitor/infrastructure/analyticsnode/details', infraAna_getAnalyticsNodeDetails);
  app.get('/api/admin/monitor/infrastructure/analyticsnode/generators', infraAna_getAnalyticsNodeGenerators);


  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/analyticsnodes', 'get', app.routes, 'analytics-node');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/analyticsnodes/summary', 'get', app.routes, 'analytics-node');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/analyticsnode/details', 'get', app.routes, 'analytics-node');
  parseURLReq.rbac.setFeatureByURL('/api/admin/monitor/infrastructure/analyticsnode/generators', 'get', app.routes, 'analytics-node');
}
infraAna_getAnalyticsNodeList = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraAna.getAnalyticsNodeList);
  }
}
infraAna_getAnalyticsNodeSummary = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraAna.getAnalyticsNodeSummary);
  }
}
infraAna_getAnalyticsNodeDetails = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraAna.getAnalyticsNodeDetails);
  }
}
infraAna_getAnalyticsNodeGenerators = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, infraAna.getAnalyticsNodeGenerators);
  }
}
