/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the featureList.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseFeatureReq = require('../../common/parseFeatureRequire')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
featureList = module.exports;

featureList.registerFeature = function() {
  parseFeatureReq.rbac.addFeatureAccess('admin-config', 'all', 'all');
  parseFeatureReq.rbac.addFeatureAccess('monitoring', 'all', 'all');
  parseFeatureReq.rbac.addFeatureAccess('orchestration', 'all', 'all');
  parseFeatureReq.rbac.addFeatureAccess('setting', 'all', 'all');
  parseFeatureReq.rbac.addFeatureAccess('proxy', 'all', 'all');
  parseFeatureReq.rbac.addFeatureAccess('alarms', 'member,cloudAdmin', 'member,cloudAdmin');
  parseFeatureReq.rbac.addFeatureAccess('discoveryclient', 'all', 'all');
}

