/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the jobProcess.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseJobsReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseJobsRequire')
  , jobsProcess = require('../../../common/api/jobsProcess.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
var jobsCb = module.exports;


var defMaxActiveJobs = 10;
var maxActiveJobs = parseJobsReq.config.maxActiveJobs || defMaxActiveJobs;

jobsCb.jobsProcess = function() {
  parseJobsReq.jobsApi.jobs.process('getTopPortByDomain', maxActiveJobs, function(job, done) {
  /* Publish the data on pubChannel And Save the data key as 
     saveChannelKey
   */
    var jobStartTime = parseJobsReq.commonUtils.getCurrentTimestamp();
    job.data['jobStartTime'] = jobStartTime;
    jobsProcess.processTopPortByDomainRequestByJob(
        job.data.taskData.pubChannel,
        job.data.taskData.saveChannelKey,
        job.data, done);
  });

  parseJobsReq.jobsApi.jobs.process('getTopPortByNetwork', maxActiveJobs, function(job, done) {
  /* Publish the data on pubChannel And Save the data key as 
     saveChannelKey
   */
    var jobStartTime = parseJobsReq.commonUtils.getCurrentTimestamp();
    job.data['jobStartTime'] = jobStartTime;
    jobsProcess.processTopPortByNetworkRequestByJob(
        job.data.taskData.pubChannel,
        job.data.taskData.saveChannelKey,
        job.data, done);
  });

  parseJobsReq.jobsApi.jobs.process('getVNFlowSeriesData', maxActiveJobs, function(job, done) {
  /* Publish the data on pubChannel And Save the data key as 
     saveChannelKey
   */
    var jobStartTime = parseJobsReq.commonUtils.getCurrentTimestamp();
    job.data['jobStartTime'] = jobStartTime;
    jobsProcess.processVNFlowSeriesDataRequestByJob(
        job.data.taskData.pubChannel,
        job.data.taskData.saveChannelKey,
        job.data, done);
  });

  parseJobsReq.jobsApi.jobs.process('getVNsFlowSeriesData', maxActiveJobs, function(job, done) {
  /* Publish the data on pubChannel And Save the data key as 
     saveChannelKey
   */
    var jobStartTime = parseJobsReq.commonUtils.getCurrentTimestamp();
    job.data['jobStartTime'] = jobStartTime;
    jobsProcess.processVNsFlowSeriesDataRequestByJob(
        job.data.taskData.pubChannel,
        job.data.taskData.saveChannelKey,
        job.data, done);
  });

  parseJobsReq.jobsApi.jobs.process('getVMFlowSeriesData', maxActiveJobs, function(job, done) {
  /* Publish the data on pubChannel And Save the data key as 
     saveChannelKey
   */
    var jobStartTime = parseJobsReq.commonUtils.getCurrentTimestamp();
    job.data['jobStartTime'] = jobStartTime;
    jobsProcess.processFlowSeriesByVMRequestByJob(
        job.data.taskData.pubChannel,
        job.data.taskData.saveChannelKey,
        job.data, done);
  });

  parseJobsReq.jobsApi.jobs.process('vnStatsPerVRouter', maxActiveJobs, function(job, done) {
  /* Publish the data on pubChannel And Save the data key as 
     saveChannelKey
   */
    var jobStartTime = parseJobsReq.commonUtils.getCurrentTimestamp();
    job.data['jobStartTime'] = jobStartTime;
    jobsProcess.processVNStatsPerVRouter(
        job.data.taskData.pubChannel,
        job.data.taskData.saveChannelKey,
        job.data, done);
  });
}

jobsCb.addjobListenerEvent = function() {
}