var pkgList = {};
exports.pkgList = pkgList;
pkgList['pkgName'] = 'webController';
pkgList['parseURL.xml'] = [];
pkgList['jobProcess.xml'] = [];
pkgList['featureList.xml'] = [];
pkgList['featureList.xml'].push('/webroot/common/api/feature.list.js');
pkgList['parseURL.xml'].push('/webroot/common/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/common/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/dns/records/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/dns/servers/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/infra/bgp/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/infra/linklocalservices/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/infra/quotas/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/infra/serviceappliance/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/infra/serviceapplianceset/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/infra/vrouters/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/fip/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/ipam/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/logicalrouter/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/networks/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/policy/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/port/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/routetable/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/routingpolicy/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/networking/securitygroup/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/physicaldevices/interfaces/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/physicaldevices/physicalrouters/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/port/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/services/bgpasaservice/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/config/services/instances/api/url.routes.js');
pkgList['jobProcess.xml'].push('/webroot/monitor/infrastructure/controlnode/jobs/jobsCb.api.js');
pkgList['parseURL.xml'].push('/webroot/config/services/templates/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/monitor/infrastructure/analyticsnode/api/url.routes.js');
pkgList['jobProcess.xml'].push('/webroot/monitor/infrastructure/vrouter/jobs/jobsCb.api.js');
pkgList['parseURL.xml'].push('/webroot/monitor/infrastructure/confignode/api/url.routes.js');
pkgList['jobProcess.xml'].push('/webroot/monitor/networking/jobs/jobsCb.api.js');
pkgList['parseURL.xml'].push('/webroot/monitor/infrastructure/controlnode/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/monitor/infrastructure/databasenode/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/monitor/infrastructure/underlay/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/monitor/infrastructure/vrouter/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/monitor/networking/api/url.routes.js');
pkgList['parseURL.xml'].push('/webroot/setting/configdb/ui/api/url.routes.js');
