/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , bgpasaserviceconfigapi = require('./bgpasaserviceconfig.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/tenants/config/get-bgp-as-a-services/:id', bgpasaserviceconfigapi_getBGPAsAServices);
  app.post('/api/tenants/config/create-bgp-as-a-service', bgpasaserviceconfigapi_createBGPAsAService);
  app.put('/api/tenants/config/update-bgp-as-a-service/:id', bgpasaserviceconfigapi_updateBGPAsAService);
  app.delete('/api/tenants/config/delete-bgp-as-a-service/:id', bgpasaserviceconfigapi_deleteBGPAsAService);


  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/get-bgp-as-a-services/:id', 'get', app.routes, 'bgpasaserviceconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/create-bgp-as-a-service', 'post', app.routes, 'bgpasaserviceconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/update-bgp-as-a-service/:id', 'put', app.routes, 'bgpasaserviceconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/delete-bgp-as-a-service/:id', 'delete', app.routes, 'bgpasaserviceconfig');
}
bgpasaserviceconfigapi_getBGPAsAServices = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, bgpasaserviceconfigapi.getBGPAsAServices);
  }
}
bgpasaserviceconfigapi_createBGPAsAService = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, bgpasaserviceconfigapi.createBGPAsAService);
  }
}
bgpasaserviceconfigapi_updateBGPAsAService = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, bgpasaserviceconfigapi.updateBGPAsAService);
  }
}
bgpasaserviceconfigapi_deleteBGPAsAService = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, bgpasaserviceconfigapi.deleteBGPAsAService);
  }
}
