/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , virtualdnsserversconfigapi = require('./virtualdnsserversconfig.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/tenants/config/virtual-DNSs', virtualdnsserversconfigapi_listVirtualDNSsFromAllDomains);
  app.post('/api/tenants/config/virtual-DNSs', virtualdnsserversconfigapi_createVirtualDNS);
  app.delete('/api/tenants/config/virtual-DNS/:id', virtualdnsserversconfigapi_deleteVirtualDNS);
  app.put('/api/tenants/config/virtual-DNS/:id/network-ipams', virtualdnsserversconfigapi_updateVDNSIpams);
  app.put('/api/tenants/config/virtual-DNS/:id', virtualdnsserversconfigapi_updateVirtualDNS);
  app.get('/api/tenants/config/sandesh/virtual-DNS/:dnsfqn', virtualdnsserversconfigapi_getVirtualDNSSandeshRecords);


  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNSs', 'get', app.routes, 'virtualdnsserversconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNSs', 'post', app.routes, 'virtualdnsserversconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id', 'delete', app.routes, 'virtualdnsserversconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/network-ipams', 'put', app.routes, 'virtualdnsserversconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id', 'put', app.routes, 'virtualdnsserversconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/sandesh/virtual-DNS/:dnsfqn', 'get', app.routes, 'virtualdnsserversconfig');
}
virtualdnsserversconfigapi_listVirtualDNSsFromAllDomains = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsserversconfigapi.listVirtualDNSsFromAllDomains);
  }
}
virtualdnsserversconfigapi_createVirtualDNS = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsserversconfigapi.createVirtualDNS);
  }
}
virtualdnsserversconfigapi_deleteVirtualDNS = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsserversconfigapi.deleteVirtualDNS);
  }
}
virtualdnsserversconfigapi_updateVDNSIpams = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsserversconfigapi.updateVDNSIpams);
  }
}
virtualdnsserversconfigapi_updateVirtualDNS = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsserversconfigapi.updateVirtualDNS);
  }
}
virtualdnsserversconfigapi_getVirtualDNSSandeshRecords = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsserversconfigapi.getVirtualDNSSandeshRecords);
  }
}
