cmd_/opt/stack/contrail/vrouter/dp-core/vr_buildinfo.o := gcc -Wp,-MD,/opt/stack/contrail/vrouter/dp-core/.vr_buildinfo.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include  -I/usr/src/linux-headers-3.13.0-100-generic/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/usr/src/linux-headers-3.13.0-100-generic/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/linux-headers-3.13.0-100-generic/include/uapi -Iinclude/generated/uapi -include /usr/src/linux-headers-3.13.0-100-generic/include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -std=gnu89 -O2 -m64 -mno-mmx -mno-sse -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -I/opt/stack/contrail/vrouter/include -I/opt/stack/contrail/build/production/vrouter/sandesh/gen-c -I/opt/stack/contrail/tools -I/opt/stack/contrail/tools/sandesh/library/c -g -Wall  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(vr_buildinfo)"  -D"KBUILD_MODNAME=KBUILD_STR(vrouter)" -c -o /opt/stack/contrail/vrouter/dp-core/.tmp_vr_buildinfo.o /opt/stack/contrail/vrouter/dp-core/vr_buildinfo.c

source_/opt/stack/contrail/vrouter/dp-core/vr_buildinfo.o := /opt/stack/contrail/vrouter/dp-core/vr_buildinfo.c

deps_/opt/stack/contrail/vrouter/dp-core/vr_buildinfo.o := \

/opt/stack/contrail/vrouter/dp-core/vr_buildinfo.o: $(deps_/opt/stack/contrail/vrouter/dp-core/vr_buildinfo.o)

$(deps_/opt/stack/contrail/vrouter/dp-core/vr_buildinfo.o):
