
/*
 * Autogenerated file. DO NOT EDIT.
 */

const char *ContrailBuildInfo = "{\"build-info\": [{\"build-time\": \"2016-11-20 01:01:08.362375\", \"build-hostname\": \"ip-172-30-14-238\", \"build-user\": \"root\", \"build-version\": \"4.0.0.0\"}]}";
