/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , physicalinterfacesconfigapi = require('./interfacesconfig.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/tenants/config/physical-interfaces/:pRouterId', physicalinterfacesconfigapi_getPhysicalInterfaces);
  app.post('/api/tenants/config/physical-interfaces/:pRouterId/:infType', physicalinterfacesconfigapi_createPhysicalInterfaces);
  app.put('/api/tenants/config/physical-interface/:pRouterId/:infType/:pInterfaceId', physicalinterfacesconfigapi_updatePhysicalInterfaces);
  app.delete('/api/tenants/config/physical-interface/:pRouterId/:infType/:pInterfaceId', physicalinterfacesconfigapi_deletePhysicalInterfaces);
  app.get('/api/tenants/config/map-virtual-machine-refs/:vmiId/:serverId', physicalinterfacesconfigapi_mapVirtualMachineRefs);
  app.delete('/api/tenants/config/li-virtual-machine/:id', physicalinterfacesconfigapi_deleteLIVirtualMachines);
  app.post('/api/tenants/config/set-vmi-refs-to-subnet/:vmiId', physicalinterfacesconfigapi_mapVMIRefsToSubnet);
  app.delete('/api/tenants/config/li-subnet/:id', physicalinterfacesconfigapi_deleteLISubnet);
  app.post('/api/tenants/config/interfaces/delete', physicalinterfacesconfigapi_deleteInterfaces);
  app.delete('/api/tenants/config/delete-all-interfaces', physicalinterfacesconfigapi_deleteAllInterfaces);
  app.post('/api/tenants/config/get-interfaces', physicalinterfacesconfigapi_getInterfaceDetails);
  app.get('/api/tenants/config/list-physical-interfaces', physicalinterfacesconfigapi_listPhysicalInterfaces);


  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/physical-interfaces/:pRouterId', 'get', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/physical-interfaces/:pRouterId/:infType', 'post', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/physical-interface/:pRouterId/:infType/:pInterfaceId', 'put', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/physical-interface/:pRouterId/:infType/:pInterfaceId', 'delete', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/map-virtual-machine-refs/:vmiId/:serverId', 'get', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/li-virtual-machine/:id', 'delete', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/set-vmi-refs-to-subnet/:vmiId', 'post', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/li-subnet/:id', 'delete', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/interfaces/delete', 'post', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/delete-all-interfaces', 'delete', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/get-interfaces', 'post', app.routes, 'physicalinterfacesconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/list-physical-interfaces', 'get', app.routes, 'physicalinterfacesconfig');
}
physicalinterfacesconfigapi_getPhysicalInterfaces = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.getPhysicalInterfaces);
  }
}
physicalinterfacesconfigapi_createPhysicalInterfaces = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.createPhysicalInterfaces);
  }
}
physicalinterfacesconfigapi_updatePhysicalInterfaces = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.updatePhysicalInterfaces);
  }
}
physicalinterfacesconfigapi_deletePhysicalInterfaces = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.deletePhysicalInterfaces);
  }
}
physicalinterfacesconfigapi_mapVirtualMachineRefs = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.mapVirtualMachineRefs);
  }
}
physicalinterfacesconfigapi_deleteLIVirtualMachines = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.deleteLIVirtualMachines);
  }
}
physicalinterfacesconfigapi_mapVMIRefsToSubnet = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.mapVMIRefsToSubnet);
  }
}
physicalinterfacesconfigapi_deleteLISubnet = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.deleteLISubnet);
  }
}
physicalinterfacesconfigapi_deleteInterfaces = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.deleteInterfaces);
  }
}
physicalinterfacesconfigapi_deleteAllInterfaces = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.deleteAllInterfaces);
  }
}
physicalinterfacesconfigapi_getInterfaceDetails = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.getInterfaceDetails);
  }
}
physicalinterfacesconfigapi_listPhysicalInterfaces = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, physicalinterfacesconfigapi.listPhysicalInterfaces);
  }
}
