/*
 * Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated from the parseURL.xml at
   Sun Nov 20 2016 01:02:58 GMT+0000 (UTC)
   Please do not edit this file.
 */

var parseURLReq = require(process.mainModule.exports["corePath"] + '/src/serverroot/common/parseURLRequire')
  , virtualdnsrecordsconfigapi = require('./virtualdnsrecordsconfig.api')
  ;


if (!module.parent) {
  console.log("Call main app through 'node app'");
  process.exit(1);
}
urlRoutes = module.exports;

/* Default handler for request timeout */
function defHandleReqTimeout (req, res)
{
  var str = "Request timed out: URL::" + req.url;
  if (req.pubChannel) {
    /* Delete the Req Pending Q Entry */
    parseURLReq.cacheApi.deleteCachePendingQueueEntry(req.pubChannel);
  };
  res.req.invalidated = true;
  res.send(parseURLReq.global.HTTP_STATUS_GATEWAY_TIMEOUT, str);
}

urlRoutes.registerURLsToApp = function(app) {
/* Register the URL with callback */
  app.get('/api/tenants/config/list-virtual-DNSs', virtualdnsrecordsconfigapi_listVirtualDNSs);
  app.post('/api/tenants/config/virtual-DNS/:id/virtual-DNS-records', virtualdnsrecordsconfigapi_updateVDNSRecordAdd);
  app.delete('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', virtualdnsrecordsconfigapi_updateVDNSRecordDelete);
  app.put('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', virtualdnsrecordsconfigapi_updateVDNSRecordUpdate);


  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/list-virtual-DNSs', 'get', app.routes, 'virtualdnsrecordsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/virtual-DNS-records', 'post', app.routes, 'virtualdnsrecordsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', 'delete', app.routes, 'virtualdnsrecordsconfig');
  parseURLReq.rbac.setFeatureByURL('/api/tenants/config/virtual-DNS/:id/virtual-DNS-record/:recordid', 'put', app.routes, 'virtualdnsrecordsconfig');
}
virtualdnsrecordsconfigapi_listVirtualDNSs = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsrecordsconfigapi.listVirtualDNSs);
  }
}
virtualdnsrecordsconfigapi_updateVDNSRecordAdd = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsrecordsconfigapi.updateVDNSRecordAdd);
  }
}
virtualdnsrecordsconfigapi_updateVDNSRecordDelete = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsrecordsconfigapi.updateVDNSRecordDelete);
  }
}
virtualdnsrecordsconfigapi_updateVDNSRecordUpdate = function(req, res, next) {
  /* Check if this request needs to be added in 
     pendingQ 
   */
  var reqCtx = parseURLReq.longPoll.routeAll(req, res, next);
  if (null == reqCtx) {
    /* either not a valid URL, or unAuthed session */
  } else {
    /* Set the request timeout */
    parseURLReq.timeout(req, res, parseURLReq.global.DFLT_HTTP_REQUEST_TIMEOUT_TIME);
    req.once('timeout', defHandleReqTimeout);
    /* Now process the resuest */
    parseURLReq.longPoll.processPendingReq(reqCtx, next, virtualdnsrecordsconfigapi.updateVDNSRecordUpdate);
  }
}
