/*
 * Copyright (c) 2016 Juniper Networks, Inc. All rights reserved.
 */

/* This file is automatically generated at
   Sun Nov 20 2016 01:16:41 GMT+0000 (UTC)
   Please do not edit this file.
 */

var config = {};
config.regionsFromConfig = false;
config.regions = {};
config.regions.RegionOne = 'http://172.30.14.238:5000/v2.0';
$(document).ready(function () {
    $("#region_id").select2({placeholder: "Select the Region", data: [], width: "283px"});
})
